##############################################################################
##############################################################################
#
# NOTE!
#
# Please read the README.md file in this directory that defines what should
# be placed in this file
#
##############################################################################
##############################################################################

name: PR Workflow

on:
  pull_request:
    branches:
      - '**'

env:
  CODECOV_UNIQUE_NAME: CODECOV_UNIQUE_NAME-${{ github.run_id }}-${{ github.run_number }}

jobs:
  CodeRabbit-Approval:
    name: Validate CodeRabbit.ai Approval
    runs-on: ubuntu-latest
    steps:
      - name: Check CodeRabbit.ai Approval
        run: |
          if ! reviews=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews"); then
            echo "Error: Failed to fetch PR reviews"
            exit 1
          fi

          if ! echo "$reviews" | jq . >/dev/null 2>&1; then
            echo "Error: Invalid JSON response from GitHub API"
            exit 1
          fi
          
          approval_count=$(echo "$reviews" | jq '[.[] | select(.state == "APPROVED" and .user.login == "coderabbitai")] | length')

          if [[ ! "$approval_count" =~ ^[0-9]+$ ]]; then
            echo "Error: Failed to parse approval count"
            exit 1
          fi

          if [[ $approval_count -eq 0 ]]; then
            echo "Error: PR is not approved by CodeRabbit.ai"
            exit 1
          else
            echo "Success: PR approved by CodeRabbit.ai"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
